In [11]:
import torch
import torch.nn as nn

In [12]:
class LinearRegressionModel(nn.Module):
    def __init__(self, input_dim, output_dim):
        super(LinearRegressionModel, self).__init__()
        self.linear = nn.Linear(input_dim, output_dim)

    def forward(self, x):
        out = self.linear(x)
        return out


In [25]:
input_dim = 1
output_dim = 1
model = LinearRegressionModel(input_dim, output_dim)
model

LinearRegressionModel(
  (linear): Linear(in_features=1, out_features=1, bias=True)
)

In [14]:
epochs = 1000
learning_rate = 0.01
optimizer = torch.optim.SGD(model.parameters(),lr = learning_rate)
criterion = nn.MSELoss()

### 训练模型

In [26]:
import numpy as np
x_values = [i for i in range(11)]
print(x_values)
x_train = np.array(x_values, dtype=np.float32)
print(x_train)
x_train.reshape(-1,1)
print(x_train)

y_values = [i*2 for i in range(11)]
print(y_values)
y_train = np.array(y_values, dtype=np.float32)
print(y_train)
y_train.reshape(-1,1)
print(y_train)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20]
[ 0.  2.  4.  6.  8. 10. 12. 14. 16. 18. 20.]
[ 0.  2.  4.  6.  8. 10. 12. 14. 16. 18. 20.]


(11,)

In [ ]:
for epoch in range(epochs):
    epoch +=1
    inputs = torch.from_numpy(x_train)
    labels = torch.from_numpy(y_train)

    optimizer.zero_grad()
    outputs = model(inputs)

    loss = criterion(outputs, labels)

    # 反向传播，计算个权重
    loss.backward()
    # 更新权重参数
    optimizer.step()
    if epoch % 50 == 0:
        print('epoch {}, loss {}'.format(epoch, loss.item()))

In [48]:
X = torch.linspace(-math.pi, math.pi, 200, device=device, dtype=dtype)
torch.randn((), device=device, dtype=dtype, requires_grad=True)
torch.tensor(0.0001,device=device, dtype=dtype, requires_grad=True)

tensor(1.0000e-04, requires_grad=True)

In [76]:
# -*- coding: utf-8 -*-
import torch
import math

dtype = torch.float
device = torch.device("cpu")
# device = torch.device("cuda:0")  # Uncomment this to run on GPU

# Create Tensors to hold input and outputs.
# By default, requires_grad=False, which indicates that we do not need to
# compute gradients with respect to these Tensors during the backward pass.
x = torch.linspace(-math.pi, math.pi, 2000, device=device, dtype=dtype)
y = torch.sin(x)

# Create random Tensors for weights. For a third order polynomial, we need
# 4 weights: y = a + b x + c x^2 + d x^3
# Setting requires_grad=True indicates that we want to compute gradients with
# respect to these Tensors during the backward pass.
a = torch.randn((), device=device, dtype=dtype, requires_grad=True)
b = torch.randn((), device=device, dtype=dtype, requires_grad=True)
c = torch.randn((), device=device, dtype=dtype, requires_grad=True)
d = torch.randn((), device=device, dtype=dtype, requires_grad=True)
e = torch.tensor(0.00000001,device=device, dtype=dtype, requires_grad=True)

learning_rate = 1e-6
for t in range(20000):
    # Forward pass: compute predicted y using operations on Tensors.
    y_pred = a + b * x + c * x ** 2 + d * x ** 3 + e * x ** 4

    # Compute and print loss using operations on Tensors.
    # Now loss is a Tensor of shape (1,)
    # loss.item() gets the scalar value held in the loss.
    loss = (y_pred - y).pow(2).sum()
    if t % 100 == 99:
        print(t, loss.item())

    # Use autograd to compute the backward pass. This call will compute the
    # gradient of loss with respect to all Tensors with requires_grad=True.
    # After this call a.grad, b.grad. c.grad and d.grad will be Tensors holding
    # the gradient of the loss with respect to a, b, c, d respectively.
    loss.backward()

    # Manually update weights using gradient descent. Wrap in torch.no_grad()
    # because weights have requires_grad=True, but we don't need to track this
    # in autograd.
    with torch.no_grad():
        a -= learning_rate * a.grad
        b -= learning_rate * b.grad
        c -= learning_rate * c.grad
        d -= learning_rate * d.grad
        e -= learning_rate * e.grad

        # Manually zero the gradients after updating weights
        a.grad = None
        b.grad = None
        c.grad = None
        d.grad = None
        e.grad = None

print(f'Result: y = {a.item()} + {b.item()} x + {c.item()} x^2 + {d.item()} x^3')

99 nan
199 nan
299 nan
399 nan
499 nan
599 nan
699 nan
799 nan
899 nan
999 nan
1099 nan
1199 nan
1299 nan
1399 nan
1499 nan
1599 nan
1699 nan
1799 nan
1899 nan
1999 nan
2099 nan
2199 nan
2299 nan
2399 nan
2499 nan
2599 nan
2699 nan
2799 nan
2899 nan
2999 nan
3099 nan
3199 nan
3299 nan
3399 nan
3499 nan
3599 nan
3699 nan
3799 nan
3899 nan
3999 nan
4099 nan
4199 nan
4299 nan
4399 nan
4499 nan
4599 nan
4699 nan
4799 nan
4899 nan
4999 nan
5099 nan
5199 nan
5299 nan
5399 nan
5499 nan
5599 nan
5699 nan
5799 nan
5899 nan
5999 nan
6099 nan
6199 nan
6299 nan
6399 nan
6499 nan
6599 nan
6699 nan
6799 nan
6899 nan
6999 nan
7099 nan
7199 nan
7299 nan
7399 nan
7499 nan
7599 nan
7699 nan
7799 nan
7899 nan
7999 nan
8099 nan
8199 nan
8299 nan
8399 nan
8499 nan
8599 nan
8699 nan
8799 nan
8899 nan
8999 nan
9099 nan
9199 nan
9299 nan
9399 nan
9499 nan
9599 nan
9699 nan
9799 nan
9899 nan
9999 nan
10099 nan
10199 nan
10299 nan
10399 nan
10499 nan
10599 nan
10699 nan
10799 nan
10899 nan
10999 nan
11099 nan
1